apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: argocd
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook
        image: jvkpsingh/addressbook:v1
        ports:
        - containerPort: 80
