apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: deploy
spec:
  type: NodePort
  selector:
    app: addressbook
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # You can change this to any valid port in the range
