apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
   app: addressbook
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007  # NodePort range is 30000-32767
